# Количество процессов — 1-2 на ядро (у тебя 2 ядра)
worker_processes auto;

events {
    # Количество одновременных соединений на один worker (обычно 1024–4096)
    worker_connections 1024;
        }

http {
    include       mime.types;
    default_type  application/octet-stream;
    #  Зоны для ограничения запросов
    limit_conn_zone $binary_remote_addr zone=addr:10m;
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;

        # Страницы ошибок
        error_page 403 /static/errors/403.html;
        error_page 404 /static/errors/404.html;
        error_page 429 /static/errors/429.html;
        error_page 500 501 502 503 504 /static/errors/500.html;


        #  Отдельный блок для API
        location /api/ {

            limit_conn addr 10;
            limit_req zone=api_limit burst=10 nodelay;

            proxy_pass http://web:8000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        #  Все статические файлы
        location /static/ {
            alias /app/static/;
            autoindex off;
        }

        location = /robots.txt {
            alias /app/static/robots.txt;
        }

        location = /ads.txt {
            alias /app/static/ads.txt;
        }

        location = /favicon.ico {alias /app/static/favicon.ico;
        }
        location = /icon.svg {alias /app/static/icon.svg;
        }
        location = /manifest.webmanifest {alias /app/static/manifest.webmanifest;
        }
        location = /android-chrome-192x192.png {alias /app/static/android-chrome-192x192.png;
        }
        location = /android-chrome-512x512.png {alias /app/static/android-chrome-512x512.png;
        }
        location = /apple-touch-icon.png {alias /app/static/apple-touch-icon.png;
        }


        # 2. Прокси доступ ко всем остальным маршрутам на FastAPI
        location / {
            proxy_pass http://web:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 3. /image-preview/ → через FastAPI (не отдаём напрямую /tmp)
        location /tmp/ {
            return 403;
        }

        location /image-preview/ {
            proxy_pass http://web:8000;
            proxy_set_header Host $host;
        }
    }
}
