events {}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        location = /robots.txt {
            alias /app/static/robots.txt;
        }

        location = /ads.txt {
            alias /app/static/ads.txt;
        }

        location = /favicon.ico {alias /app/static/favicon.ico;
        }
        location = /icon.svg {alias /app/static/icon.svg;
        }
        location = /manifest.webmanifest {alias /app/static/manifest.webmanifest;
        }
        location = /android-chrome-192x192.png {alias /app/static/android-chrome-192x192.png;
        }
        location = /android-chrome-512x512.png {alias /app/static/android-chrome-512x512.png;
        }
        location = /apple-touch-icon.png {alias /app/static/apple-touch-icon.png;
        }


        # 1. Статические файлы: js, css, img — отдаёт напрямую
        location /static/ {
            alias /app/static/;
            autoindex off;
        }

        # 2. Прокси доступ ко всем остальным маршрутам на FastAPI
        location / {
            proxy_pass http://web:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 3. /image-preview/ → через FastAPI (не отдаём напрямую /tmp)
        location /tmp/ {
            return 403;
        }

        location /image-preview/ {
            proxy_pass http://web:8000;
            proxy_set_header Host $host;
        }
    }
}
